ansible_ssh_private_key_file: "{{ lookup('env', 'WORKER_SSH_KEY_PATH') }}"
ansible_ssh_user: "{{ lookup('env', 'WORKER_SSH_USER') | default('worker', true) }}"
service_user: "{{ ansible_ssh_user }}"
service_group: "{{ ansible_ssh_user }}"
