- name: Remove temporary values file for helm chart
  ansible.builtin.file:
    path: "{{ helm_values_temp_file }}"
    state: absent
  listen: helm_cleanup_values_file 

- name: Remove temporary values fragments for helm chart
  ansible.builtin.file:
    path: "{{ temp_directory }}/values_fragments"
    state: absent
  listen: helm_cleanup_values_fragments
