- name: Add home-k8s repo to helm
  kubernetes.core.helm_repository:
    name: home-k8s-charts
    repo_url: https://parksbra.github.io/home-k8s-charts
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Create values file
  ansible.builtin.include_role:
    name: values
  vars:
    requested_values_templates:
      - home-k8s

- name: Install home-k8s/homeassistant via helm
  kubernetes.core.helm:
    name: homeassistant
    chart_ref: home-k8s-charts/homeassistant
    namespace: "{{ homeassistant_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    update_repo_cache: true
    state: present

- name: Install home-k8s/mosquitto via helm
  kubernetes.core.helm:
    name: mosquitto
    chart_ref: home-k8s-charts/mosquitto
    namespace: "{{ homeassistant_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    update_repo_cache: true
    state: present

- name: Install home-k8s/zigbee2mqtt via helm
  kubernetes.core.helm:
    name: zigbee2mqtt
    chart_ref: home-k8s-charts/zigbee2mqtt
    namespace: "{{ homeassistant_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    update_repo_cache: true
    state: present

- name: Install home-k8s/network via helm
  kubernetes.core.helm:
    name: network
    chart_ref: home-k8s-charts/network
    namespace: "{{ homeassistant_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    update_repo_cache: true
    state: present
