# - name: Create environment namespace
#   import_tasks: create_namespace.yml

- name: Create k8s secrets for homeassistant
  import_tasks: create_secrets.yml

- name: Install helm charts for homeassistant environment
  import_tasks: install_charts.yml
