# - name: Create environment namespace
#   import_tasks: create_namespace.yml

- name: Install helm charts for homeassistant environment
  ansible.builtin.include_tasks: install_homeassistant_chart.yml

- name: Create k8s secrets for homeassistant
  ansible.builtin.include_tasks: create_secrets.yml

- name: Install mosquitto chart
  ansible.builtin.include_tasks: mosquitto.yml

- name: Install zigbee2mqtt chart
  ansible.builtin.include_tasks: zigbee2mqtt.yml
