- hosts: k8s_controller
  roles:
    - {role: kubernetes_dashboard, tags: ['kubernetes_dashboard']}
    - {role: cert_manager, tags: ['cert_manager']}
    - {role: akri_tf, tags: ['akri']}
    - {role: homeassistantenv, tags: ['homeassistantenv']}
  become: true
  become_user: root
