- hosts: k8s_controller
  roles:
    - {role: kubernetes_dashboard, tags: ['kubernetes_dashboard']}
    - {role: cert_manager, tags: ['cert_manager']}
    - {role: akri, tags: ['akri']}
    - {role: homeassistant_environment, tags: ['homeassistant_environment']}
  become: true
  become_user: root
