- name: Create Cloudflare dns api token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cert_manager_cloudflare_secret_name }}"
        namespace: "{{ cert_manager_namespace }}"
      type: Opaque
      stringData:
        {{ cert_manager_cloudflare_secret_key }}: "{{ cert_manager_cloudflare_api_token }}"
    kubeconfig: "{{ k8s_kubectl_config_path }}"

- name: Create cluster issuer for cert-manager
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ cert_manager_cluster_issuer_name }}"
      spec:
        acme:
          email: "{{ cert_manager_cloudflare_email }}"
          server: "{{ cert_manager_cluster_issuer_acme_server }}"
          privateKeySecretRef:
            name: "{{ cert_manager_cluster_issuer_private_key_secret_name }}"
          solvers:
            - dns01:
                cloudflare:
                  email: "{{ cert_manager_cloudflare_email }}"
                  apiTokenSecretRef:
                    name: "{{ cert_manager_cloudflare_api_token_secret_name }}"
                    key: "{{ cert_manager_cloudflare_secret_key }}"
    kubeconfig: "{{ k8s_kubectl_config_path }}"
