- name: Add akri repo to helm
  kubernetes.core.helm_repository:
    name: akri
    repo_url: https://project-akri.github.io/akri
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Create values file
  ansible.builtin.include_role:
    name: helm_values
  vars:
    requested_values_templates:
      - akri

- name: Install akri via helm
  kubernetes.core.helm:
    name: akri
    chart_ref: akri/akri
    namespace: akri
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    update_repo_cache: true
    state: present
